"""
Django settings for my_blog_project project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/

# ## https://github.com/Apress/beg-django-cms/blob/master/978-1-4842-1670-5-source/myblog/settings.py
"""

import os 
from pathlib import Path
from django.utils.translation import gettext_lazy as _
gettext = lambda s: s

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+)0vos6@f()*xs-+&o52!0j=d$yd=k6bf^p@7=+7jm#r4gg=w%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [  '*' ]

X_FRAME_OPTIONS = 'SAMEORIGIN'
SITE_ID = 1

TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
    'django.template.loaders.eggs.Loader'
)



MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'my_blog_app', 'media')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,   'staticfiles') ## python manage.py collectstatic will creat this dir and store all satic files from all application hre

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'my_blog_app',  'static'), #he my_blog_app static files path application
)


# Application definition

INSTALLED_APPS = [
    'djangocms_admin_style',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'cms',
    'menus',
    'treebeard',
    'sekizai',

    # -- my applications ---
    'my_blog_app'


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',

    'django.middleware.locale.LocaleMiddleware'
]


ROOT_URLCONF = 'my_blog_project.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [    
            os.path.join(BASE_DIR, 'my_blog_app', 'templates' ),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sekizai.context_processors.sekizai',
                'cms.context_processors.cms_settings',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_blog_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': { # This is th default database, you can keep only this in django (but in djangocms it won't work, you need the second below)
        'ENGINE': os.environ.get("DJANGO_SETTING_DATABASE_ENGINE"),
        'NAME': os.environ.get("DJANGO_SETTING_DATABASE_NAME"),
        'HOST': os.environ.get("DJANGO_SETTING_DATABASE_HOST"), #this must be he same as database service name inside your docker-compose file
        'PASSWORD':  os.environ.get("DJANGO_SETTING_DATABASE_ROOT_PASSWORD"),
        'PORT': os.environ.get("DJANGO_SETTING_DATABASE_PORT"),
        'USER': os.environ.get("DJANGO_SETTING_DATABASE_ROOT_USER")
    },

    '{}'.format(os.environ.get("DJANGO_SETTING_DATABASE_NAME")): {#if we don't set this, djangocms won't work
        'ENGINE': os.environ.get("DJANGO_SETTING_DATABASE_ENGINE"),
        'NAME': os.environ.get("DJANGO_SETTING_DATABASE_NAME"),
        'HOST': os.environ.get("DJANGO_SETTING_DATABASE_HOST"), #this must be he same as database service name inside your docker-compose file
        'PASSWORD':  os.environ.get("DJANGO_SETTING_DATABASE_ROOT_PASSWORD"),
        'PORT': os.environ.get("DJANGO_SETTING_DATABASE_PORT"),
        'USER': os.environ.get("DJANGO_SETTING_DATABASE_ROOT_USER")
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LANGUAGE_CODE = 'en-us'

LANGUAGES = (
    ## Customize this
    ('en-us', _('American English')),
    ('en', _('English')),
    ('de', _('Deutsch')),
    ('fr', _('French'))
)

CMS_LANGUAGES = {
    ## Customize this
    'default': {
        'public': True,
        'hide_untranslated': False,
        'redirect_on_fallback': True,
    },
    1: [
        {
            'public': True,
            'code': 'en',
            'hide_untranslated': False,
            'name': gettext('en'),
            'redirect_on_fallback': True,
        },

        {
            'public': True,
            'code': 'en-us',
            'hide_untranslated': False,
            'name': gettext('en-us'),
            'redirect_on_fallback': True,
        },

        {
            'public': True,
            'code': 'de',
            'hide_untranslated': False,
            'name': gettext('de'),
            'redirect_on_fallback': True,
        },

        {
            'public': True,
            'code': 'fr',
            'hide_untranslated': False,
            'name': gettext('fr'),
            'redirect_on_fallback': True,
        },
    ],
}

CMS_TEMPLATES = [
    ('blog/child.html', 'Page Home'),
    #('blog/home.html', 'Page Home'),
    #('utils/page.html', 'Page'),
    #('blog/blogpage.html', 'Blog Page with Sidebar')
]


